main_category:
  10:
    name: Fruits
    sub_categories:
      10001: Mango
      10002: Orange 
  11:
    name: Fish 
    sub_categories:
      11001: Salmon
      11002: Bass
  12:
    name: Vegetables 
    sub_categories:
      12001: Carrot
      12002: Onion

categories:
  10001: Mango
  10002: Orange
  11001: Salmon
  11002: Bass
  12001: Carrot
  12002: Onion

category_items:
  i_10001:
    cat_name: Mango
    items:
      1: Green Mango
      2: Sweet Mango
  i_10002:
    cat_name: Orange 
    items:
      3: Sunkist Orange 
      4: Ponkan Orange
